version: '3.8'
services:
  api:
    build: ./server
    volumes: 
      - logs:/app/logs
      - /app/node_modules

  client:
    build: ./client
    stdin_open: true
    tty: true
    depends_on: 
      - api

  nginx:
    build: ./nginx
    ports:
      - 9097
    restart: always
    depends_on:
      - api
      - client
  
volumes: 
  logs:
