apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: sajedul2024/reactproject:bck
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: back-clusterip
spec:
  selector:
    app: server
  ports:
  - port: 3005
    targetPort: 3005
