apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: sajedul2024/reactproject:bck
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: front-clusterip
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
  - port: 3000
    targetPort: 3000